# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: tkoyama010@gmail.com
author_name: Tetsuo Koyama
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: server
labextension_name: myextension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: myextension
repository: https://github.com/tkoyama010/myextension.git
test: true
viewer_name: ''

